<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('services')->delete();

        // ID Category 2 = Cuci Satuan (asumsi kategori sudah ada di tabel service_categories)
        $categoryId = 2; 

        $services = [
            // --- CUCI SELIMUT ---
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Selimut (Express 4 Jam)',
                'slug' => 'cuci-selimut-express-4-jam',
                'description' => 'Layanan super kilat cuci selimut selesai dalam 4 Jam.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 100000.00,
                'min_weight_kg' => null,
                'duration_hours' => '4',
                'duration_label' => '4 Jam',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Selimut (Kilat 8 Jam)',
                'slug' => 'cuci-selimut-kilat-8-jam',
                'description' => 'Layanan kilat cuci selimut selesai dalam 8 Jam.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 75000.00,
                'min_weight_kg' => null,
                'duration_hours' => '8',
                'duration_label' => '8 Jam',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Selimut (Cepat 12 Jam)',
                'slug' => 'cuci-selimut-cepat-12-jam',
                'description' => 'Layanan cepat cuci selimut selesai dalam 12 Jam.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 60000.00,
                'min_weight_kg' => null,
                'duration_hours' => '12',
                'duration_label' => '12 Jam',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Selimut (Reguler 1 Hari)',
                'slug' => 'cuci-selimut-reguler-1-hari',
                'description' => 'Layanan cuci selimut standar selesai dalam 1 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 50000.00,
                'min_weight_kg' => null,
                'duration_hours' => '24',
                'duration_label' => '1 Hari (24 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Selimut (Reguler 2 Hari)',
                'slug' => 'cuci-selimut-reguler-2-hari',
                'description' => 'Layanan cuci selimut hemat selesai dalam 2 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 40000.00,
                'min_weight_kg' => null,
                'duration_hours' => '48',
                'duration_label' => '2 Hari (48 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Selimut (Santai 3 Hari)',
                'slug' => 'cuci-selimut-santai-3-hari',
                'description' => 'Layanan cuci selimut paling hemat selesai dalam 3 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 30000.00,
                'min_weight_kg' => null,
                'duration_hours' => '72',
                'duration_label' => '3 Hari (72 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- CUCI HELM ---
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Helm (Reguler 1 Hari)',
                'slug' => 'cuci-helm-reguler-1-hari',
                'description' => 'Layanan cuci helm bersih dan wangi selesai dalam 1 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 35000.00,
                'min_weight_kg' => null,
                'duration_hours' => '24',
                'duration_label' => '1 Hari (24 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Helm (Reguler 2 Hari)',
                'slug' => 'cuci-helm-reguler-2-hari',
                'description' => 'Layanan cuci helm hemat selesai dalam 2 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 25000.00,
                'min_weight_kg' => null,
                'duration_hours' => '48',
                'duration_label' => '2 Hari (48 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Helm (Santai 3 Hari)',
                'slug' => 'cuci-helm-santai-3-hari',
                'description' => 'Layanan cuci helm paling hemat selesai dalam 3 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 20000.00,
                'min_weight_kg' => null,
                'duration_hours' => '72',
                'duration_label' => '3 Hari (72 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- CUCI SEPATU WARNA ---
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Sepatu Warna (Reguler 1 Hari)',
                'slug' => 'cuci-sepatu-warna-reguler-1-hari',
                'description' => 'Layanan cuci sepatu warna selesai dalam 1 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 50000.00,
                'min_weight_kg' => null,
                'duration_hours' => '24',
                'duration_label' => '1 Hari (24 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Sepatu Warna (Reguler 2 Hari)',
                'slug' => 'cuci-sepatu-warna-reguler-2-hari',
                'description' => 'Layanan cuci sepatu warna hemat selesai dalam 2 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 40000.00,
                'min_weight_kg' => null,
                'duration_hours' => '48',
                'duration_label' => '2 Hari (48 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Sepatu Warna (Santai 3 Hari)',
                'slug' => 'cuci-sepatu-warna-santai-3-hari',
                'description' => 'Layanan cuci sepatu warna paling hemat selesai dalam 3 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 30000.00,
                'min_weight_kg' => null,
                'duration_hours' => '72',
                'duration_label' => '3 Hari (72 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- CUCI SEPATU PUTIH ---
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Sepatu Putih (Reguler 1 Hari)',
                'slug' => 'cuci-sepatu-putih-reguler-1-hari',
                'description' => 'Layanan treatment khusus cuci sepatu putih selesai dalam 1 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 55000.00,
                'min_weight_kg' => null,
                'duration_hours' => '24',
                'duration_label' => '1 Hari (24 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Sepatu Putih (Reguler 2 Hari)',
                'slug' => 'cuci-sepatu-putih-reguler-2-hari',
                'description' => 'Layanan treatment khusus cuci sepatu putih hemat selesai dalam 2 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 45000.00,
                'min_weight_kg' => null,
                'duration_hours' => '48',
                'duration_label' => '2 Hari (48 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $categoryId,
                'name' => 'Cuci Sepatu Putih (Santai 3 Hari)',
                'slug' => 'cuci-sepatu-putih-santai-3-hari',
                'description' => 'Layanan treatment khusus cuci sepatu putih paling hemat selesai dalam 3 Hari.',
                'pricing_type' => 'by_unit',
                'price_per_kg' => null,
                'price_per_unit' => 35000.00,
                'min_weight_kg' => null,
                'duration_hours' => '72',
                'duration_label' => '3 Hari (72 Jam)',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('services')->insert($services);
    }
}
